export const USER_LOGGED_IN = 'USER_LOGGED_IN'
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT'
export const LOADING_USER = 'LOADING_USER'
export const USER_LOADED = 'USER_LOADED'

export const SET_VIAGEM = 'SET_VIAGEM'
export const SET_VIAGENS_FILTRADAS = 'SET_VIAGENS_FILTRADAS'
export const LOAD_VIAGENS_NAO_CONCLUIDAS = 'LOAD_VIAGENS_NAO_CONCLUIDAS'
export const LOAD_VIAGENS_CONCLUIDAS = 'LOAD_VIAGENS_CONCLUIDAS'
export const INICIAR_VIAGEM = 'INICIAR_VIAGEM'
export const CONCLUIR_VIAGEM = 'CONCLUIR_VIAGEM'

export const INICIANDO_VIAGEM = 'INICIANDO_VIAGEM'
export const VIAGEM_INICIADA = 'VIAGEM_INICIADA'

export const SET_MENSAGEM = 'SET_MENSAGEM'

export const CARREGANDO_VEICULO = 'CARREGANDO_VEICULO'
export const VEICULO_CARREGADO = 'VEICULO_CARREGADO'
export const SET_VEICULOS_DISPONIVEIS = 'SET_VEICULOS_DISPONIVEIS'