export const USER_LOGGED_IN = 'USER_LOGGED_IN'
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT'

export const INICIAR_VIAGEM = 'INICIAR_VIAGEM'
export const CONCLUIR_VIAGEM = 'CONCLUIR_VIAGEM'

export const SET_MENSAGEM = 'SET_MENSAGEM'